### PR TITLE
Skip firewall checks if there is no VPC

### LINKED ISSUE #25: Controls for firewall rules should be skipped if there is no VPC in project
Especially applicable for shared VPC setups.

1.2.rb

### PR DESCRIPTION
**Pull request by KonradSchieban**
fixes https://github.com/GoogleCloudPlatform/inspec-gcp-pci-profile/issues/25

### CODE REVIEW

**Comment by aaronlippold** [comment]
Are we sure these shouldn't be set to non applicable aka impact zero when they skip or is it truly an absent subcomponent

**Comment by KonradSchieban** [comment]
> Are we sure these shouldn't be set to non applicable aka impact zero when they skip or is it truly an absent subcomponent

@aaronlippold would you suggest to rather skip each check with zero impact than skip all at once at the top?

**Review by binamov — APPROVED** [review]

**Pull request merged**
