### PR TITLE
respectful code cleanup

### LINKED ISSUE #38: Respectful code cleanup: 6 instances of negative terms found
Avoic the following terms:

white list
whitelist

These were found in the following file(s):

controls/10.5.rb
controls/10.2.rb
controls/3.5.rb

### PR DESCRIPTION
**Pull request by KonradSchieban**
Closes https://github.com/GoogleCloudPlatform/inspec-gcp-pci-profile/issues/38

/gcbrun

### CODE REVIEW

**Comment by aaronlippold** [comment]
Shouldn't this be, 'ensure an allowed list... '

**Comment by aaronlippold** [comment]
Right now the sentence isn't a sentence :-)

**Comment by KonradSchieban** [comment]
I considered "allowlist" a proper noun :) is it not?
... in any case it should be "an allow..."

**Pull request merged**
